#!/bin/bash
#
#################################Start script and validation####################################
if [[ $EUID -ne 0 ]]; 
then echo -e "Script must be run as root!"
exit 1
else

echo "Starting the installation of your Openvpn server"
apt-get install openvpn -y 
cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0 /etc/openvpn/easy-rsa
echo "Please fill in the information as following"
echo "KEY_COUNTRY=? (US is default)"
read country
sed -i -e "s/KEY_COUNTRY=\"US\"/KEY_COUNTRY=$country/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_PROVINCE=? (CA is default)" 
read province
sed -i -e "s/KEY_PROVINCE=\"CA\"/KEY_PROVINCE=$province/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_CITY=? (SanFrancisco is default)" 
read city
sed -i -e "s/KEY_CITY=\"SanFrancisco\"/KEY_CITY=$city/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_ORG=? (ex: Company-name)" 
read org
sed -i -e "s/KEY_ORG=\"Fort-Funston\"/KEY_ORG=$org/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_EMAIL=? (ex: your@email.com)" 
read mail
sed -i -e "s/KEY_EMAIL=\"me@myhost.mydomain\"/KEY_EMAIL=$mail/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_EMAIL=? (ex: your@email.com)" 
read email
sed -i -e "s/KEY_EMAIL=mail@host.domain/KEY_EMAIL=$email/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_CN=? (ex: server.hostname.com)" 
read key_cn
sed -i -e "s/KEY_EMAIL=changeme/KEY_EMAIL=$key_cn/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_NAME=? (ex: server.hostname.com)" 
read key_name
sed -i -e "s/KEY_NAME=changeme/KEY_EMAIL=$key_name/" /etc/openvpn/easy-rsa/vars
#
echo "KEY_OU=? (ex: OrganisationUnitname)" 
read key_ou
sed -i -e "s/KEY_OU=changeme/KEY_OU=$key_ou/" /etc/openvpn/easy-rsa/vars
#
#################Clearing whichopensslcnf#########
#working on a fix
sed -i "s/\[\[:alnum\:\]\]//" /etc/openvpn/easy-rsa/2.0/whichopensslcnf
#################Clean all########################
/etc/openvpn/easy-rsa/2.0/clean-all
#
/etc/openvpn/easy-rsa/2.0/build-ca
#
echo "Server name? (server.hostname.com)"
read server.hostname.com
/etc/openvpn/easy-rsa/2.0/build-key-server $server.hostname.com
#
exit
fi
