#!/bin/bash
#
#################################Start script and validation####################################
#if [ -f /usr/bin/apt-get ]; then
#echo "* Installing OpenVPN server."
# apt-get install openvpn -y > /dev/null 2>&1
# mkdir /etc/openvpn/easy-rsa
# cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0 /etc/openvpn/easy-rsa/
#elif [ -f /usr/bin/yum ]; then
# echo "* Installing OpenVPN server."
# yum install openvpn -y > /dev/null 2>&1
# mkdir /etc/openvpn/easy-rsa
# cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0 /etc/openvpn/easy-rsa/
#else
# echo "Unsupported distribution."
# exit 1
#fi

###Starting###
#In this part we will make the directories needed#
	if [[ $EUID -ne 0 ]];
			then echo -e "Script must be run as root!"
				exit 1
			else
		echo "* Starting the installation of your OpenVPN server"
			apt-get install openvpn -y
		mkdir /etc/openvpn/easy-rsa
			cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0 /etc/openvpn/easy-rsa/
###Configuring###
#In this part we will configure the files#
	echo "* Please fill in the information as following"
		echo "KEY_COUNTRY=? (US is default)"
			read COUNTRY
		echo "KEY_PROVINCE=? (CA is default)"
			read PROVINCE
		echo "KEY_CITY=? (SanFrancisco is default)"
			read CITY
		echo "KEY_ORG=? (ex: Company-name)"
			read ORG
		echo "KEY_EMAIL=? (ex: your@email.com)"
			read MAIL
		echo "KEY_EMAIL=? (ex: your@email.com)"
			read EMAIL
		echo "KEY_CN=? (ex: server.hostname.com)"
			read KEYCN
		echo "KEY_NAME=? (ex: server.hostname.com)"
			read KEYNAME
		echo "KEY_OU=? (ex: OrganisationUnitname)"
			read ORGNAME
###Replacing##
	sed -i -e "s/KEY_COUNTRY=\"US\"/KEY_COUNTRY=$COUNTRY/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_PROVINCE=\"CA\"/KEY_PROVINCE=$PROVINCE/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_CITY=\"SanFrancisco\"/KEY_CITY=$CITY/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_ORG=\"Fort-Funston\"/KEY_ORG=$ORG/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_EMAIL=\"me@myhost.mydomain\"/KEY_EMAIL=$MAIL/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_EMAIL=mail@host.domain/KEY_EMAIL=$EMAIL/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_CN=changeme/KEY_CN=$KEYCN/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_NAME=changeme/KEY_NAME=$KEYNAME/" /etc/openvpn/easy-rsa/2.0/vars
	sed -i -e "s/KEY_OU=changeme/KEY_OU=$ORGNAME/" /etc/openvpn/easy-rsa/2.0/vars
#################Clearing whichopensslcnf#########
#This will allow it to properly detect the version of OpenSSL on your computer#
sed -i "s/\[\[:alnum\:\]\]//" /etc/openvpn/easy-rsa/2.0/whichopensslcnf
#################Clean all########################
source /etc/openvpn/easy-rsa/2.0/vars
	bash /etc/openvpn/easy-rsa/2.0/clean-all
	bash /etc/openvpn/easy-rsa/2.0/build-ca
		echo -e "* we are now creating the server, whats the name?"
			bash /etc/openvpn/easy-rsa/2.0/build-key-server server
		echo -e "* we will generate one client to begin with"
			bash /etc/openvpn/easy-rsa/2.0/build-client1
				bash /etc/openvpn/easy-rsa/2.0/build-dh
	cp /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz /etc/openvpn
		gunzip /etc/openvpn/server.conf.gz
################Editing server.conf####################
IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }') 
	sed_exec=$(echo $IP | sed -i -e "s/;local a.b.c.d/local $IP/" /etc/openvpn/server.conf)
GW=$(route -n | grep 'UG[ \t]' | awk '{print $2}')
	sed -i -e "s/;push \"route 192.168.10.0 255.255.255.0\"/push \"route $GW 255.255.255.0\"/" /etc/openvpn/server.conf
	sed -i 's/;user nobody/user nobody/g' /etc/openvpn/server.conf
	sed -i 's/;group nogroup/group nogroup/g' /etc/openvpn/server.conf
################Moving keys and files#################
cp keys/ca.crt /etc/openvpn
cp keys/server.{key,crt} /etc/openvpn
cp keys/dh1024.pem /etc/openvpn
cp keys/ca.crt /home/$USER
cp keys/client1.crt /home/$USER
cp keys/client1.key /home/$USER
################Final instructions####################
#
#
exit
fi
